version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 5
    rebase-strategy: auto
    groups:
      github-actions-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]
    labels: [dependencies, automated-maintenance]
    commit-message:
      prefix: deps
  - package-ecosystem: pip
    directory: "/compute-center"
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 5
    rebase-strategy: auto
    groups:
      compute-center-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]
    labels: [dependencies, automated-maintenance, compute-center]
    commit-message:
      prefix: deps-compute
